\documentclass{article}
\usepackage{url}
\usepackage{breakurl}
%\VignetteIndexEntry{The DMRcate package user's guide}
%\VignetteEngine{knitr::knitr}
\begin{document}
\title{The \texttt{DMRcatedata} package user's guide}

\author{Peters TJ, Buckley MJ, Pidsley R, Clark SJ, Molloy PL}
\maketitle

\section*{Package Contents}

\texttt{DMRcatedata} accompanies the \texttt{DMRcate} package, providing data for examples and probe filtering.

<<libr, message=FALSE, warning=FALSE>>=
library(DMRcatedata)
data(dmrcatedata)
@

Three objects are contained in \texttt{DMRcatedata}. 
\texttt{crosshyb} is a factor listing probe IDs potentially confounded by cross-hybridisation to other parts of the genome\cite{Chen}. It is used internally by \texttt{rmSNPandCH()}.

<<crosshyb>>=
str(crosshyb)
@

\texttt{illuminaSNPs} is a data.frame containing probes that are potentially confounded by a SNP. It lists the SNPID, distance (in nucleotides) to the CpG in question, and minor allele frequency for each associated SNP

<<illuminaSNPs>>=
class(illuminaSNPs)
dim(illuminaSNPs)
head(illuminaSNPs)
@

\texttt{myBetas} is a matrix of 450K probe beta values, matching to Homo Sapiens chromosome 20, sourced from the colon and rectal adenocarcinoma section of The Cancer Genome Atlas (TCGA) Repository. It contains 38 matched tumour/normal pairs. 

<<myBetas>>=
class(myBetas)
dim(myBetas)
@

\section*{Sources}
\begin{itemize}
  \item \texttt{myBetas} sourced from The Cancer Genome Atlas (TCGA) data repository, colon and rectal adenocarcinoma
  \item \texttt{illuminaSNPs} sourced from \url{http://supportres.illumina.com/documents/myillumina/88bab663-307c-444a-848e-0ed6c338ee4d/humanmethylation450_15017482_v.1.2.snpupdate.table.v3.txt}, accessed February 2014
  \item \texttt{crosshyb} sourced from \url{http://www.sickkids.ca/MS-Office-Files/Research/Weksberg Lab/48639-non-specific-probes-Illumina450k.xlsx}, accessed February 2014
\end{itemize}

\begin{thebibliography}{9}

\bibitem{Chen}
  Chen YA, Lemire M, Choufani S, Butcher DT, Grafodatskaya D, Zanke BW, Gallinger S, Hudson TJ, Weksberg R. 
  Discovery of cross-reactive probes and polymorphic CpGs in the Illumina Infinium HumanMethylation450 microarray. 
  \emph{Epigenetics}. 2013 Jan 11;8(2).

\end{thebibliography}

\end{document}